[login]
username = "admin"
password = "password123"

[openai]
api_key = "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"

[google]

  type: "service_account",
  project_id: "analiseb2",
  private_key_id: "25a0d9190c00bc77e90c2ba0612b333d7b0bf401",
  private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC3MQ0wfl9GpEwk\n6OZj0YBpxVPt8mQ4IHNSyEi/56AykIOQz8UZgoIcMRWnxxMjIsnspm1G5/2JVTtX\nSXUbpCVVzaNMvxM3fKTCO8ToFGk/3j9lmTtOXL0s9gOED2vHlBGGEzVwOFV2UpmI\nDYqAx+kCEGw1nEF3B+qtP84L+PvdQYwcRH/f9t3xZUqFZMyQk1oz9AeLlltyG3wi\ne6XrBh/8ja5ZWLsD8eAgJ5pjTbVKAUcO06dg13/WWWwDUGdqCkQaM3riJhLqQwNx\neFaATFzud/EobgJbJrGSiO2L6qJRnXvWz+TdhAFPw6bw9bC0gd9PetvKjH/0LfYZ\nLtGB6oLrAgMBAAECggEACKCkRODmvs51EZXwZ8oRmKmk8sNkKeqJU+A/4N3ZQxhg\nQd0vJKzrUMWVBgJPqet1BBKwedLqM2ISueEpRUR9R6W4J6CmGIpjvgwPkXiInmvq\no2/MhbvDYw8xCjKpukwEaUKVVTQp/jkUpv4wRDFmDWVVm07BHIiAamljXFf9EKX1\nmlaWv/GbtSKGgSgceD/YaquddOa/KEcvNNr0luWXO2f5cp3UVvgFWG1YXrYfDY8M\n2PoGivgNyxjeOaUDr2nINRIi91ArQxMO23A/rrRSBiOEuCkC9nhUZip8J8UWptxU\nCCBni9Jc2sl1cbeZFjBPnhDTHdtKziZvYq1BxOso0QKBgQDyigA1hWkIRpidLK8m\nr5Oet/E8eIZ3TYtlH9WFyWdfQPVGzfdHZyn+jo2ttS/U6ewHvtd93pGnvwGqG5H0\nRZVUy836pn611NjiDt1rcargTUAGGl+Q9i4hNKlqIu8bhc3yqhqbOc+aNLNGD07m\nye6zkaKKBymQ8aw7rVYMRom8ewKBgQDBW9dMLP1BI8A5a5G5QePu3ZbgGU6sXMTi\nNu4qQzJWUZQahoFt5/qoLWRHKj1p9f3oLgfllHh1Vh3Lu5lY8FSeczxRNYvctgFB\nkSBxzNDzvNWk1G8kl3/vlZQCdLLVovam3x8QzjhOoB5AhQCBsRAuKDkDsy3Lw6iK\nwwxdX8ugUQKBgCpt+/Vg/mvlNcOhUo7Y/mEw2rHyf8uVNEKfnBIIlt3yFjapx42l\nPZJ7y8tMvC5qMdF1EGvDqQWIg7kHk7QBDEvGT6V+xQH4V2zMnu2x9+u/d+jZakiI\n2K8UcGLR87SD5vCB05++MFRQzd/+w5XaU7j0TFQLRrlFnhTekQQavvPLAoGBAJHK\nM61GBrYExL0GtFtgqQHDpizWKBGh6Pk/vZe0DtIytF7Dp/c8gCwp/YADA0dPqOBV\nRLL/nUurYM/qZRdALi1Caeo5W3lQ6eWMDVCAw9PjP5sGab7HVDlLKMwpPWYDd8Ie\nXYgIVUBDTkwLfHRNEwwaW9LEWPVYU048/qewwRHhAoGAO4k6t6O5/W0d7OTOODPg\nSyZWgtZBxohSA1yI2E7au55meIsfam9brt+O7VmVah1gbArG2aBSQuHZYhzbzhd7\nWFSV67F5qSZQesC7L6M7cgTDjIY1wK5QX/FL8YeXyQ7yMFA4hgnyDwg7akrCNNdj\nivYEGqscAMJ4KeKKE9pSQOc=\n-----END PRIVATE KEY-----\n",
  client_email: "streamlit-app@analiseb2.iam.gserviceaccount.com",
  client_id: "111977506245002472675",
  auth_uri: "https://accounts.google.com/o/oauth2/auth",
  token_uri: "https://oauth2.googleapis.com/token",
  auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs",
  client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-app%40analiseb2.iam.gserviceaccount.com",
  universe_domain: "googleapis.com"


